services:
  # Backend Service
  - type: web
    name: autoprocure-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements-render.txt
    startCommand: chmod +x backend/start-render.sh && ./backend/start-render.sh
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.kycsdqamiacdgcjhkedp:Vishak%406@aws-0-a
      - key: AI_PROVIDER
        value: ollama
      - key: AI_MODEL
        value: mistral
      - key: OLLAMA_URL
        value: http://localhost:11434
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Service
  - type: web
    name: autoprocure-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://autoprocure-backend.onrender.com 