services:
  - type: web
    name: autoprocure-backend
    env: python
    buildCommand: pip install -r requirements.txt && cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Goberian%4006@db.kycsdqamiacdgcjhkedp.supabase.co:5432/postgres
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: FROM_EMAIL
        value: noreply@autoprocure.com
      - key: FROM_NAME
        value: AutoProcure